Rc/0.3.0 (#82)
* add deps command

* add package class

* add earthmover deps function

* add GitPython, required for package install

* add package config file variable to package class

* Add draft groupby_with_rank operation

* eliminate packages list in favor of graph

* add root package type, rename destination_path

* add package merge steps to compile and run

* add package merge functionality

* updates for compatibility with merge functionality

* reorder and update comments

* Add group_by with rank operation

* added group_by_with_rank

* added null date feature

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* fixed error

* added errors='coerce'

* added NaT

* added pandas.NaT

* fixed error

* changed to pd

* fixed error

* fixed error

* fixed error

* removed to dataframe

* fixed error

* fixed error

* added errors ignore

* added to frame

* Add explicit fillna on Source load.

* added ignore error flag

* added ignore_errors flag

* added space

* removed unnecessary operations

* added exact clause for dates with different formats

* added exact clause for dates with differing formats

* Add optional_fields config to Sources; add missing fields to dataframe if not present.

* check for cycles

* throw more helpful error when packages have not been installed

* remove symlink in favor of local copy

* added source extension

* Update destination.py

This hotfix addresses a bug I encountered when trying to load assessments into SC using a Snowflake-sourced ID-xwalk. 

```
TypeError: Cannot setitem on a Categorical with a new category (), set the categories first
```

For some reason, a Categorical column in being introduced during processing, and must be converted to a string before filling NAs.

* Update destination.py

Update fillna datatype from str to "string" to keep nulls.

* Update VERSION.txt

* Remove force-fillna on sources.

* Add logging to optional column additions.

* Force dataframe to string type to circumvent type mismatches.

* Force dataframe joins to strings.

* update yaml output format and macro handling

* add yaml loading step to package class

* reorder yaml load process to ensure macros are handled correctly

* fixes for transformation path replacement

* update name of output file

* add project composition to readme

* refactor git install to allow a branch to be specified

* Revert merge datatype updates (they don't work anyway).

* Add 'optional_fields' to allowed_configs for all sources.

* Update CHANGELOG.

* Remove hashing on file source directories, and log accordingly when hashing is attempted in these cases.

TODO: Should we actually try to hash directories?

* Move 'operation' into 'operations' subfolder.

* Move 'node' into 'nodes' subfolder.

* Minor cleanup to ignore_errors flag; update README with additions.

* Update changelog with DateFormatOperation updates.

* Output the head of the dataframe when logging level is set to DEBUG, or if debug is turned on for an individual node.

* Refactor debug head logging to only output once and to output all columns without the index.

* Update CHANGELOG.md.

* Update CHANGELOG.md.

* quick dedup print

* added set

* undo

* Move YamlMapping utility methods into class.

* bugfix: ignore map_values operation with no map_file

* add example project

* Minor bugfix.

* Add file metadata to YamlMapping object and update error_handling logging to use it.

* Fix bug where operations were poorly labeled in logging.

* Update VERSION.txt to 0.3.0.

* Move destination string cleanup within render lambda.

* Remove string-force in source to allow categorical memory saving from SQL sources.

* Force datatype of empty optional dataframes to strings.

* Update test 2 to verify null values are processed correctly.

* Minor bugfix.

* Rc/0.3.0  refactor build graph (#79)

* Add comments and clean up main.

* Add helper method to Node to improve logging.

* Refactor compile and graph-building for improved logging and tracing.

* Create Earthmover.load_project_configs().

* Unify Earthmover.compile() and Earthmover.build_graph(); lazy-init config attributes.

* Minor cleanup.

* Separate node compilation logic into helper method.

* Force transformation context to reset before checking in graph; add comments.

* Add type-hints.

* Move filter_graph_on_selector() logic into nearly-static method. Reapply original graph arguments to execute() and hash_graph_to_runs_file.

* Convert Node.full_name from a property to an attribute; move Node.set_upstream_source() to bottom of file.

* Rename outputted Earthmover template to 'earthmover_compiled.yaml' instead of 'earthmover_composed.yml'; output a warning instead of an error if `earthmover deps` is called with no packages.

* Update CHANGELOG.md.

* Rc/0.3.0  refactor build graph  merge compile (#80)

* Unify compile() into init() for all nodes.

* Update CHANGELOG.md.

* Minor bugfix.

* Force line-endings to LF. (#81)

* Add extras to Earthmover for installing optional packages. (#73)

* Add extras to Earthmover for installing optional packages.

TODO: what versions to attach, how to handle additional graph-draing libraries, what others to include?

* Add extra for XML.

* Add excel optional install.

* Rename 'sql' extra to 'postgres'; add 'git' extra; add 'pygraphviz' to 'graph' extra.

* Update Graph.draw() package checks to suggest new installation extras path for graph dependency installs; update GraphViz error call to only give command for installing GraphViz.

* Remove git installation extra.

* Add more explicit package install messages when attempting to load sources without requires packages.

* Re-add generic sql install extra.

* Minor bugfix on FileSource._verify_packages()

* Add installation package checks for SqlSource.

* Update CHANGELOG.md.

* Force Node.num_rows from float to int.

* Remove Node.compile(): somehow this change was missed during merges.

* Force downgrade of dask[dataframe] to circumvent null divisions bug in empty dataframes.

* Force num_rows and num_cols to 0 during compile graph draw.

* Remove unused group_by_with_count and group_by_with_agg operations.

* Force Dask version to latest allowed version for Python 3.8.

* Remove incorrect entry from CHANGELOG.md.

---------

Co-authored-by: sleblanc23 <sam23leblanc@gmail.com>
Co-authored-by: Ryan Aguilar <raguilar@edanalytics.org>
Co-authored-by: Angelica Lastra <angelicaalastra@gmail.com>